version: 2.1
jobs:
  minsar-testing:
    machine:
      image: default

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
              - "SHA256:UQXk8EzF60pAQ4fbeZgkWDcI3OMEXV5LcyuK6KJzJy8"
      - run:
          name: Set up Enviornment
          command: |
            echo "Working directory: ${PWD}"
            ./setup/install_python.bash
            ./setup/install_minsar.bash
            ./setup/install_sarvey.bash
            ./setup/install_vsm.bash
            minsar/bin/minsarApp.bash --help
            echo "alias s.bw2m='export MINSAR_HOME=${CIRCLE_WORKING_DIRECTORY}; source project/setup/environment.bash'" >> ~/.bashrc

      - run:
          name: Prepare test data (Sentinel-1)
          command: |
            export MINSAR_HOME=${CIRCLE_WORKING_DIRECTORY}
            source setup/platforms_defaults.bash;
            source setup/environment.bash

            wget -O- http://149.165.154.65/data/circleci/ci_small_unittestGalapagosSenDT128.tar | tar -xvf - -C ${SCRATCHDIR}
            wget -O- http://149.165.154.65/data/circleci/S1orbits_unittestGalapagosSenDT128.tar | tar -xvf - -C "$(dirname ${SENTINEL_ORBITS})"
            
            minsarApp.bash ${MINSAR_HOME}/samples/circleci/ci_unittestGalapagosSenDT128.template --no-orbit-download --start dem --stop jobfiles
            
workflows:
  version: 2
  testing:
    jobs:
      - minsar-testing
